name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures the full repository history is fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this matches your local Node.js version

      - name: Install Dependencies
        run: npm ci # Clean install of dependencies

      - name: Build Project
        run: npm run build # Build your project, ensure the build script is correct

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
          publish_dir: ./build # Directory where the build output is located
          publish_branch: gh-pages # Branch where the site will be published


